networks:
  default:
    name: gw_net

services:
  gw:
    image: "${IMAGE}"
    restart: ${RESTART}
    container_name: gw${ID}
    volumes:
      - ./logs:/var/logs
      - ./browsing:/var/browsing:ro
      - ./baresip:/var/baresip:ro
      - ./ivr:/var/ivr:ro
    devices:
      - /dev/video${ID}:/dev/video0
    shm_size: '2gb'
    logging:
      driver: syslog
      options:
        tag: "{{.ImageName}}/{{.Name}}"
    environment:
      TZ: "${HOST_TZ}" # Time Zone
      GW_ID: "${ID}"
      SIP_ACCOUNT: "${ACCOUNT}" # <sip:user@domain;transport=tcp>;auth_pass=pass;answermode=auto;medianat=turn;stunserver=turn:turnserver.org:3478;stunuser=username;stunpass=passwd
      BROWSE_FILE: "jitsi.py" # python browsing based on Selenium
      WEBRTC_DOMAIN: "rendez-vous.renater.fr" # WebRTC domain name (only for Jitsi web conferences)
      ROOM_NAME: "${ROOM}" # for a BBB webconference, something like "gl/tiz-bel-zkk-qh3" is expected
      FROM_URI: "${FROM}" # SIP URI of the caller
      BARESIP_ARGS: "" # Add Baresip arguments e.g. " -v" (=> full logs)
      ERR_LOGS: "/dev/stderr"
      APP_LOGS: "/dev/stdout"
    stop_grace_period: 20s
