networks:
  default:
    name: gw_net
    external: true

services:
  gw:
    image: "${DOCKER_IMAGE}"
    restart: ${RESTART}
    container_name: gw${ID}
    networks:
      default:
        aliases:
          - "${ROOM}"
    tmpfs:
      - /tmp
    volumes:
      - ./logs:/var/logs
      - ./streaming/streaming.sh:/var/streaming/streaming.sh
      - ./entrypoint.sh:/var/entrypoint.sh
      - ./src/eventServer.py:/var/src/eventServer.py
      - ./src/event_handler.py:/var/src/event_handler.py
      - ./src/netstring.py:/var/src/netstring.py
    devices:
      - /dev/${ID:+video}${ID:-null}:/dev/video0
      - /dev/snd:/dev/snd
    shm_size: '2gb'
    logging:
      driver: syslog
      options:
        tag: "{{.ImageName}}/{{.Name}}"
    env_file:
      - .env
      - deploy/.env_kamailio
      - deploy/.env_turn
    stop_grace_period: 20s
