networks:
  default:
    external:
      name: gw_net

services:
  gw:
    image: sipmediagw
    container_name: gw${ID}
    volumes:
            - ./logs:/var/logs
            - ./browsing:/var/browsing:ro
            - ./baresip:/var/baresip:ro
            - ./ivr:/var/ivr:ro
    devices:
            - /dev/video${ID}:/dev/video0
            - /dev/snd:/dev/snd
    environment:
      TZ: "${HOST_TZ}" # Time Zone
      GW_ID: "${ID}"
      LOG_PREF: "${LOGS}"
      SIP_ACCOUNT: "${ACCOUNT}" # <sip:user@domain;transport=tcp>;auth_pass=pass;answermode=auto;medianat=turn;stunserver=turn:turnserver.org:3478;stunuser=username;stunpass=passwd
      BROWSE_FILE: "rendezvousjitsi.py" # python browsing based on Selenium
      ROOM_NAME: "${ROOM}" # for a BBB webconference, something like "gl/tiz-bel-zkk-qh3" is expected
      FROM_URI: "${FROM}" # SIP URI of the caller
    stop_grace_period: 20s

