networks:
  default:
    name: gw_net
services:
  baresip:
    image: baresip
    build:
        context: .
        dockerfile: Dockerfile
    container_name: baresip
    stdin_open: true
    tty: true
    volumes:
            - .baresip:/var/.baresip:ro
    command:
            - /bin/sh
            - -c
            - "baresip -f /var/.baresip -v ${DIAL}"


